spring:
  application:
    name: task-manager-demo
  datasource:
    url: jdbc:h2:mem:taskmanagerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE
    driverClassName: org.h2.Driver
    username: user
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none # Remove Hibernate schema generation so that it can be handled by Liquibase.
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml